---
id: lilo-20171217
base_name: lilo-20171217
tags:
- debian
presentation_date: 2017/12/17
version: 2017.12.17
licenses: []
slideshare_id: lilolinuxorjp-201712
speaker_deck_id: lilo-dot-linux-dot-or-dot-jp-falsehua-2017nian-12yue
ustream_id:
vimeo_id:
youtube_id:
author:
  markup_language: :markdown
  name: Kazuhiro NISHIYAMA
  email: zn@mbf.nifty.com
  rubygems_user: znz
  slideshare_user: znzjp
  speaker_deck_user: znz
